"""Initial migration

Revision ID: 190d5771044f
Revises: 
Create Date: 2024-03-04 13:15:23.072540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190d5771044f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('charities',
    sa.Column('charity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('charity_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('beneficiaries',
    sa.Column('beneficiary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('inventory_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.PrimaryKeyConstraint('beneficiary_id')
    )
    op.create_table('donations',
    sa.Column('donation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('payment_method', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_table('donor_payment_methods',
    sa.Column('method_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_name', sa.String(length=255), nullable=False),
    sa.Column('payment_method_details', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('method_id')
    )
    op.create_table('inventory_items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('quantity_requested', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('payment_transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=255), nullable=True),
    sa.Column('transaction_status', sa.String(length=255), nullable=True),
    sa.Column('date_paid', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('regular_donations',
    sa.Column('donation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_table('reminder_settings',
    sa.Column('setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('setting_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('stories',
    sa.Column('story_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.create_table('words_of_support',
    sa.Column('support_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.charity_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('support_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words_of_support')
    op.drop_table('stories')
    op.drop_table('reviews')
    op.drop_table('reminder_settings')
    op.drop_table('regular_donations')
    op.drop_table('payment_transactions')
    op.drop_table('items')
    op.drop_table('inventory_items')
    op.drop_table('donor_payment_methods')
    op.drop_table('donations')
    op.drop_table('beneficiaries')
    op.drop_table('users')
    op.drop_table('charities')
    op.drop_table('admins')
    # ### end Alembic commands ###
